### PR TITLE
Fix for validation failure of Packed_Data_Fields and bit fields (#209)

### LINKED ISSUE #209: Packed_Data_Fields and bit fields do not validate as expected
**Describe the bug**
From Dick Simpson:

Upon encountering  Field_Binary.Packed_Data_Fields,  Validate becomes confused and returns error messages of the form

      ERROR  [error.table.field_value_overlap]   table 6, record 1, field 2: The field is overlapping with the next field. Current field ends at 8. Next field starts at 4

where no such overlap exists.  From the typical error message, it appears that Validate is ignoring the content of the Field_Binary with packed data and is not adjusting the pointer to the correct beginning of the next field.  It also appears that Validate is not distinguishing between fields and bit fields; and it is not able to parse at finer resolution than integer bytes.

Validate operation on the attached product   odf07155.{dat,xml}   generates 33,589 error messages of the type above (see  odf07155-report.docx,  also attached).  

I recommend first studying records in Tables 8, 10, and 12 (which all have the same format); each is short and has only a pair of bit fields in Field_Binary #5.  Records in Table 6 are more complex; they have 4 instances of packed data (out of 7 Field_Binary objects).  Those packed data objects have between 2 and 9 bit fields, each of which can have a length between 1 and 24 bits.  I have attached a spreadsheet outlining the structures in this product type (Record_Structure_with_Bit_Fields.xlsx).

This error makes validation of migrated radio science data from missions prior to 2019 impossible in most cases, since the ODF (Orbit Data File) was very common when there was a gravity investigation (most missions start with gravity, then add other radio science investigations).  Prior to 2001, all radio science investigations had products with bit fields.  Going forward, bit fields are likely to be uncommon; but they are an option for certain radio science investigations with high sampling rates.  They might also be chosen for mapping radar instruments, and they may occur in spacecraft telemetry data.

**Test Data**
[bit_field_issue.tar.gz](https://github.com/NASA-PDS-Incubator/validate/files/4432584/bit_field_issue.tar.gz)

**See #209 for additional details for a similar issue**

### PR DESCRIPTION
**Pull request by hhlee445**
Resolves #209

Test data can be found in https://github.com/NASA-PDS/validate/tree/master/src/test/resources

### CODE REVIEW

**Comment by jordanpadams** [comment]
Previous updates disabled checks for overlapping Field_Binary, which is still something we want to check. New updates include checks for overlapping bit fields as well as Field_Binary.

Commit includes broken tests due to other PR being works.

```
PDS Validate Tool Report

Configuration:
   Version                       1.23.0-SNAPSHOT
   Date                          2020-05-08T22:41:03Z

Parameters:
   Targets                       [file:/Users/jpadams/Documents/proj/pds/pdsen/workspace/validate/src/test/resources/github209/VALID_odf07155_msgr_11.xml]
   Severity Level                WARNING
   Recurse Directories           true
   File Filters Used             [*.xml, *.XML]
   Data Content Validation       on
   Product Level Validation      on
   Max Errors                    100000
   Registered Contexts File      /Users/jpadams/Documents/proj/pds/pdsen/workspace/validate/validate-1.23.0-SNAPSHOT/resources/registered_context_products.json



Product Level Validation Results

  FAIL: file:/Users/jpadams/Documents/proj/pds/pdsen/workspace/validate/src/test/resources/github209/VALID_odf07155_msgr_11.xml
    Begin Content Validation: file:/Users/jpadams/Documents/proj/pds/pdsen/workspace/validate/src/test/resources/github209/odf07155.dat
      ERROR  [error.table.records_mismatch]   table 13: Number of records read is not equal to the defined number of records in the label (expected 2406, got 2464).
    End Content Validation: file:/Users/jpadams/Documents/proj/pds/pdsen/workspace/validate/src/test/resources/github209/odf07155.dat
        1 product validation(s) completed

Summary:

  1 error(s)
  0 warning(s)

  Product Validation Summary:
    0          product(s) passed
    1          product(s) failed
    0          product(s) skipped

  Referential Integrity Check Summary:
    0          check(s) passed
    0          check(s) failed
    0          check(s) skipped

  Message Types:
    1            error.table.records_mismatch

End of Report
Completed execution in 6761 ms
```

**Comment by jordanpadams** [comment]
@hhlee445 just so you are aware ☝️

**Comment by rchenatjpl** [comment]
The attached should validate but doesn't.
% validate -t val224.xml
PDS Validate Tool Report
Configuration:
   Version                       1.24.0-SNAPSHOT
   Date                          2020-05-12T07:18:23Z
Parameters:
   Targets                       [file:/Users/rchen/Desktop/val224.xml]
   Severity Level                WARNING
   Recurse Directories           true
   File Filters Used             [*.xml, *.XML]
   Data Content Validation       on
   Product Level Validation      on
   Max Errors                    100000
   Registered Contexts File      /PDS4tools/validate/resources/registered_context_products.json
Product Level Validation Results
  FAIL: file:/Users/rchen/Desktop/val224.xml
    Begin Content Validation: file:/Users/rchen/Desktop/val224.bin
      ERROR  [error.table.field_value_overlap]   table 1, record 1, field 44: The field is overlapping with the next field. Current field ends at 92. Next field starts at 88
    End Content Validation: file:/Users/rchen/Desktop/val224.bin
        1 product validation(s) completed
Summary:
  1 error(s)
  0 warning(s)
  Product Validation Summary:
    0          product(s) passed
    1          product(s) failed
    0          product(s) skipped
  Referential Integrity Check Summary:
    0          check(s) passed
    0          check(s) failed
    0          check(s) skipped
  Message Types:
    1            error.table.field_value_overlap
End of Report
Completed execution in 9888 ms

If I change line 438 from 1 to 6 (anything but 1) and line 445 from 2 to 7, this validates
[Archive.zip](https://github.com/NASA-PDS/validate/files/4613983/Archive.zip)

**Comment by rchenatjpl** [comment]
And can I make a suggestion on the language? "The field is overlapping with the next field" should be "This field overlaps the next field"

**Comment by rchenatjpl** [comment]
Another problem, possibly related. The first error is the same false error as above, but the next two errors are real, but "field 50" and "field 68" in the error message are wrong. They should be something like "field 45.2" and "field 45.20" or "binary field 45, bit field 2" and "binary field 45, bit field 20".

% validate -t val224.xml
PDS Validate Tool Report
Configuration:
   Version                       1.24.0-SNAPSHOT
   Date                          2020-05-12T07:54:37Z
Parameters:
   Targets                       [file:/Users/rchen/Desktop/val224.xml]
   Severity Level                WARNING
   Recurse Directories           true
   File Filters Used             [*.xml, *.XML]
   Data Content Validation       on
   Product Level Validation      on
   Max Errors                    100000
   Registered Contexts File      /PDS4tools/validate/resources/registered_context_products.json
Product Level Validation Results
  FAIL: file:/Users/rchen/Desktop/val224.xml
    Begin Content Validation: file:/Users/rchen/Desktop/val224.bin
      ERROR  [error.table.field_value_overlap]   table 1, record 1, field 44: The field is overlapping with the next field. Current field ends at 92. Next field starts at 88
      ERROR  [error.table.field_value_overlap]   table 1, record 1, field 50: The bit field is overlapping with the next field. Current stop_bit_location: 4. Next start_bit_location: 4
      ERROR  [error.table.field_value_overlap]   table 1, record 1, field 68: The bit field is overlapping with the next field. Current stop_bit_location: 27. Next start_bit_location: 27
    End Content Validation: file:/Users/rchen/Desktop/val224.bin
        1 product validation(s) completed
Summary:
  3 error(s)
  0 warning(s)
  Product Validation Summary:
    0          product(s) passed
    1          product(s) failed
    0          product(s) skipped
  Referential Integrity Check Summary:
    0          check(s) passed
    0          check(s) failed
    0          check(s) skipped
  Message Types:
    3            error.table.field_value_overlap
End of Report
Completed execution in 4049 ms

[Archive.zip](https://github.com/NASA-PDS/validate/files/4614142/Archive.zip)

**Pull request merged**
