### PR TITLE
New requirement to ensure is exactly one digit to the left of the decimal point for the specifier `e` or `E` and fix tests

### LINKED ISSUE #992: As a user, I want to validate that there is exactly one digit to the left of the decimal point for the specifier `e` or `E`
### Checked for duplicates

Yes - I've already checked

### 🧑‍🔬 User Persona(s)

Archivist

### 💪 Motivation

In SR 4B.1.2 Field Formats, for the specifier "e,E", exactly one digit is always to the left of the decimal point, so 333.3e33 is illegal, i.e. that ought to be 3.333e35.

### 📖 Additional Details

_No response_

### Acceptance Criteria

**Given** a label with a field format containing the specifier `e` or `E`, and >1 digit to the left of the decimal point (e.g. 333.3e33)
**When I perform** validate on the label
**Then I expect** validate to throw an error

**Given** a label with a field format containing the specifier `e` or `E`, and <1 digit to the left of the decimal point (e.g. .3e33)
**When I perform** validate on the label
**Then I expect** validate to throw an error

### ⚙️ Engineering Details

_No response_

### 🎉 I&T

_No response_

### PR DESCRIPTION
**Pull request by al-niessner**
## 🗒️ Summary
Fix field regular expresion

## ⚙️ Test Data and/or Report
All automated unit/regression tests pass

## ♻️ Related Issues
Closes #992

### CODE REVIEW

**Review by nutjob4life — COMMENTED** [review]
@al-niessner am I running these tests wrong?
```console
$ echo $JAVA_HOME
/Library/Java/JavaVirtualMachines/jdk-17.0.1.jdk/Contents/Home
$ mvn --version
Java version: 17.0.1, vendor: Oracle Corporation, runtime: /Library/Java/JavaVirtualMachines/jdk-17.0.1.jdk/Contents/Home
Default locale: en_US, platform encoding: UTF-8
OS name: "mac os x", version: "15.0.1", arch: "x86_64", family: "mac"
$ git status
On branch issue_992
Your branch is up to date with 'origin/issue_992'.

nothing to commit, working tree clean
$ mvn clean test
[INFO] Scanning for projects...
[INFO] Inspecting build with total of 1 modules...
[INFO] Installing Nexus Staging features:
[INFO]   ... total of 1 executions of maven-deploy-plugin replaced with nexus-staging-maven-plugin
[INFO] 
[INFO] -----------------------< gov.nasa.pds:validate >------------------------
[INFO] Building gov.nasa.pds:validate 3.6.0-SNAPSHOT
[INFO]   from pom.xml
[INFO] --------------------------------[ jar ]---------------------------------
[INFO] 
[INFO] --- clean:3.2.0:clean (default-clean) @ validate ---
[INFO] Deleting /Users/kelly/Documents/Clients/JPL/PDS/Development/nasa-pds/validate/target
[INFO] 
[INFO] --- buildnumber:3.2.1:create (default) @ validate ---
[INFO] Storing buildNumber: 2024-10-22 17:00:52 at timestamp: 1729634452655
[INFO] Executing: /bin/sh -c cd '/Users/kelly/Documents/Clients/JPL/PDS/Development/nasa-pds/validate' && 'git' 'symbolic-ref' 'HEAD'
[INFO] Working directory: /Users/kelly/Documents/Clients/JPL/PDS/Development/nasa-pds/validate
[INFO] Storing scmBranch: issue_992
…
[ERROR] Tests run: 270, Failures: 60, Errors: 0, Skipped: 23
[INFO] 
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  10:29 min
[INFO] Finished at: 2024-10-22T17:11:17-05:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:3.3.0:test (default-test) on project validate: There are test failures.
[ERROR] 
[ERROR] Please refer to /Users/kelly/Documents/Clients/JPL/PDS/Development/nasa-pds/validate/target/surefire-reports for the individual test results.
[ERROR] Please refer to dump files (if any exist) [date].dump, [date]-jvmRun[N].dump and [date].dumpstream.
[ERROR] -> [Help 1]
…
```

**Comment by al-niessner** [comment]
No. Something is deeply broken within the test portion of this repo.

**Comment by nutjob4life** [comment]
@al-niessner no worries, no rush! I'll stand by for now. (Well, not really … I'll _sit_ by because I'm already on my chair 😆)

**Comment by al-niessner** [comment]
@jordanpadams @nutjob4life @tloubrieu-jpl 

Can I please get a quick review and merge so that I can repair some of the other branches. Thanks.

**Comment by nutjob4life** [comment]
You got it @al-niessner! I just pulled and am running `mvn test`.

**Review by nutjob4life — APPROVED** [review]
@al-niessner good news!
```
[INFO] Tests run: 233, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 511.2 s -- in cucumber.CucumberTest
[INFO] 
[INFO] Results:
[INFO] 
[WARNING] Tests run: 264, Failures: 0, Errors: 0, Skipped: 23
[INFO] 
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  10:07 min
[INFO] Finished at: 2024-10-24T12:24:34-05:00
[INFO] ------------------------------------------------------------------------
```
Let's merge this already! 👍 🎉

**Pull request merged**
