### PR TITLE
add unit test first

### LINKED ISSUE #923: Configuration file parser does not reject incorrect options
### Checked for duplicates

Yes - I've already checked

### 🐛 Describe the bug

I received a report from a data provider about unusual errors that they were encountering with validate. One of the issues that showed up in the report indicated that their schemas were not being loaded. The configuration file that they provided indicated that they used the option "validate_schema" instead of "validate.schema", so the schemas were not being loaded correctly.

### 🕵️ Expected behavior

I expected validate to fail when it encounters configuration options that it cannot handle.

### 📜 To Reproduce

create a configuration file that uses validate_schema instead of validate.schema and save it to config.txt
run `validate -c config.txt -t target`
Look for the " User Specified Schemas " section at the top of the report, which will be missing.

### 🖥 Environment Info

- Version of this software validate3.5.1
- Operating System: MacOSX with openjdk 21.0.3
...

### 📚 Version of Software Used

validate 3.5.1

### 🩺 Test Data / Additional context

_No response_

### 🦄 Related requirements

🦄 #xyz

### ⚙️ Engineering Details

_No response_

### 🎉 Integration & Test

_No response_

### PR DESCRIPTION
**Pull request by al-niessner**
## 🗒️ Summary
Added additional check that values in the config file are understood.

## ⚙️ Test Data and/or Report
Automated unit/regression tests below should pass

## ♻️ Related Issues
Closes #923

### CODE REVIEW

**Comment by al-niessner** [comment]
@jordanpadams these errors are not related to my changes. Something going on with PDS website like it is down or something?

**Review by nutjob4life — APPROVED** [review]

**Comment by nutjob4life** [comment]
Clicked wrong button, didn't mean to approve a draft PR (GitHub UI makes this all too easy)

**Comment by jordanpadams** [comment]
@al-niessner JAXA website appears to have an expired certificate. [Commented out that test case](https://github.com/NASA-PDS/validate/commit/2fd8259ddf63e439d7a2cacd0acb8e68fe6e9e27) for now, which will hopefully fix it.

**Comment by jordanpadams** [comment]
@al-niessner you can rebase your branch and try again

**Comment by al-niessner** [comment]
@jordanpadams @nutjob4life 

Killing this branch. Do not need the unit test because the exception thrown when keyword is not know is not catchable by cucumber or at least I do not think it is since it parses log files for validate errors not raw java exceptions. Anyway, it is a waste of space if want a unit test I  can write a better one.

**Pull request closed without merging**
