### PR TITLE
Upgrades of libraries to support regression when introducing colliding JAXB libraries

### PR DESCRIPTION
**Pull request by al-niessner**
## 🗒️ Summary
Reduced JAXB to a single version.

## ⚙️ Test Data and/or Report
Unit testing below should all pass - finally

## ♻️ Related Issues
NA

### CODE REVIEW

**Comment by al-niessner** [comment]
YAY!! It works correctly in eclipse now too! When I say that, the cucumber runs as a junit suite and they all show as valid; meaning, it is using the expected and actual error counts with types correctly. Never did that before.

**Comment by al-niessner** [comment]
@jordanpadams @nutjob4life 

Please review so I can merge then rebase/merge other branches. Thanks.

**Review by jordanpadams — APPROVED** [review]

**Comment by jordanpadams** [comment]
🚢

**Review by nutjob4life — COMMENTED** [review]
Looks good to me:
```
Tests run: 268, Failures: 0, Errors: 0, Skipped: 23
```
👍

**Pull request merged**
