### PR TITLE
Issue #42: Add capability to ignore product-level validation

### LINKED ISSUE #42: Add capability to pds4.bundle validation to ignore product-level validation
Per request from several node personnel, they would like the ability to ignore product-level validation when they run pds4.bundle or pds4.collection validation. This would allow them to run a parallel instance of validate that performs the product-level validation.

### PR DESCRIPTION
**Pull request by hhlee445**
Add capability to pds4.bundle validation to ignore product-level validation.

Resolves #42

### CODE REVIEW

**Comment by jordanpadams** [comment]
@hhlee445 sorry for being a stickler here. but since the there are no unit/regression tests, can you please add a comment to this PR that includes test results (e.g. how you ran validate and the output results) and the test data you used? @galenatjpl

**Review by jordanpadams — CHANGES_REQUESTED** [review]
See previous posted comment.

**Comment by jordanpadams** [comment]
@hhlee445 it doesn't look like this works as expected. Using the bundle in https://starbase.jpl.nasa.gov/pds4/1900/dph_examples_v1900.zip as test data, 

When I run pds4.bundle validation with product level validation I get:
```
./validate -R pds4.bundle -t ~/Downloads/V1900/dph_example_archive/ --no-data-check
...
Summary:

  1 error(s)
  53 warning(s)

  Message Types:
    1            error.label.schema
    53           warning.integrity.member_not_found
```

But when I run it with `skip-product-validation` I get:
```
./validate -R pds4.bundle -t ~/Downloads/V1900/dph_example_archive/ --skip-product-validation
...
Summary:

  0 error(s)
  104 warning(s)

  Message Types:
    69           warning.integrity.member_not_found
    35           warning.file.not_referenced_in_label
```

From the `warning.integrity.member_not_found` I think we are not opening the XML at all, when in actuality, we do want to do this member check, we just don't want to do any other validation of the labels (e.g. context resolution, resource resolution, etc.) . Does that make sense?

For `warning.file.not_referenced_in_label` I think we will also want to disable the rule that executes `FindUnreferencedFiles` when this flag is enabled.

**Review by jordanpadams — CHANGES_REQUESTED** [review]
See previous comment

**Comment by hhlee445** [comment]
I will check again.

The log shows that skip-product-validation flag now: 

./validate -R pds4.bundle -t ~/Downloads/V1900/dph_example_archive/ --skip-product-validation
...
Summary:

  1 error(s)
  53 warning(s)

  Message Types:
    1            error.label.schema
    53           warning.integrity.member_not_found

End of Report

**Comment by jordanpadams** [comment]
@hhlee445 I think it is still doing`LabelValidationRule` at the product level. after digging into this a bit, we may need to sit down with @mcayanan and figure out the best approach here. since all XML are treated equally as "targets", when we get to `LabelValidationRule` there is no way currently to say "this label is a bundle or collection label" and then ignore all the others.

When I ran validation on the V1900 bundle with some debug messages added, I see this:
```
  PASS: file:/Users/jpadams/Downloads/V1900/dph_example_archive/data_imagecube/virs/virs_wavelengths.xml
class gov.nasa.pds.tools.validate.rule.RegisterTargets
class gov.nasa.pds.tools.validate.rule.pds4.LabelInFolderRule
class gov.nasa.pds.tools.validate.rule.pds4.LabelValidationRule
class gov.nasa.pds.tools.validate.rule.pds4.FileReferenceValidationRule
```

I am going to descope this from this build and we will try to figure it out for next build.

**Comment by mcayanan** [comment]
@hhlee445 @jordanpadams To ignore product-level validation, my recommendation would be to look at [validation-commands.xml](https://github.com/NASA-PDS-Incubator/validate/blob/master/src/main/resources/validation-commands.xml) and find out which of the product-level validation rules you want to ignore. For this ticket, it would seem like you'd be focusing on the `pds4.label` area. One of the rules is `LabelValidationRule` so you would update the `isApplicable` method https://github.com/NASA-PDS-Incubator/validate/blob/90e35c408100bcbaec9fbd37078fd04d936a8b5e/src/main/java/gov/nasa/pds/tools/validate/rule/pds4/LabelValidationRule.java#L89 and check to see if the `--skip-product-validation` is set. If it is, then you can return `false` and this rule would get ignored. Then Validate will move to the next rule on that list...Note that part of what this rule does is it returns a parsed label which I'm pretty sure is assumed to exist in some of the other rules that follow this. So you may need to update the downstream rules accordingly to handle the case where a parsed label does not exist....Anyways, if you have more questions feel free to let me know and we can talk more about this.

**Comment by hhlee445** [comment]
As Mike's suggestion, --skip-product-validation flag is checked in LabelValidationRule java class and the log shows 

% ./bin/validate -R pds4.bundle -t /Users/hyunlee/dev/pds_en/validate/issue_42/V1900/dph_example_archive/ --skip-product-validation
PDS Validate Tool Report

…

PDS4 Bundle Level Validation Results

  …

Summary:

  0 error(s)
  69 warning(s)

  Message Types:
    69           warning.integrity.member_not_found

End of Report

**Comment by hhlee445** [comment]
After talking with Mike, additional check was added in parseAndValidate method (in LabelValidator class).

% ./bin/validate -R pds4.bundle -t /Users/hyunlee/dev/pds_en/validate/issue_42/V1900/dph_example_archive/ --skip-product-validation
PDS Validate Tool Report

…

Summary:

  0 error(s)
  53 warning(s)

  Message Types:
    53           warning.integrity.member_not_found

End of Report

**Comment by jordanpadams** [comment]
Closing for rebased branch and PR #109

**Pull request closed without merging**
