### PR TITLE
Skip delimited table offset check when no `object_length` is given

### LINKED ISSUE #781: Validate making incorrect assumption that first object has and object length == `file_size`
### Checked for duplicates

Yes - I've already checked

### 🐛 Describe the bug

When I did ran validate against a product with numerous objects and a `file_size` defined, it seems that Validate expects the first object to be that length.

### 🕵️ Expected behavior

I expected `file_size` to mean all objects combined

### 📜 To Reproduce

See https://github.com/NASA-PDS/validate/issues/684#issuecomment-1835702898

### 🖥 Environment Info

Mac OSx

### 📚 Version of Software Used

gov.nasa.pds:validate
Version 3.4.0-SNAPSHOT
Release Date: 2023-12-04 07:19:11

### 🩺 Test Data / Additional context

See See https://github.com/NASA-PDS/validate/issues/684#issuecomment-1835702898

### 🦄 Related requirements

_No response_

### ⚙️ Engineering Details

_No response_

### I&T
TestRail Test ID: T8681196

### PR DESCRIPTION
**Pull request by al-niessner**
## 🗒️ Summary
#684 was about over specification. This is about under specification. Changes to fix this are in NASA-PDS/pds4-jparser#109

## ⚙️ Test Data and/or Report
All automated unit tests below should pass

## ♻️ Related Issues
Closes #781 
#684 
NASA-PDS/pds4-jparser#109

### CODE REVIEW

**Comment by al-niessner** [comment]
@jordanpadams 

The actual fix will be in jparser. I see that it works on this example but cannot test it in regression because mvn test always uses the downloaded artifact rather than my local stuff. I will push the jparser stuff then need you to make a new build of it or let me do it then rerun these tests to make sure did not break anything else.

**Comment by jordanpadams** [comment]
@al-niessner copy that. I think if you run `mvn install` on pds4-jparser first, it should work, but maybe not...

**Comment by al-niessner** [comment]
@jordanpadams 

Did mvn install and it succeeded but it does not appear to be visible to this branch. Made it locally maybe?

**Comment by al-niessner** [comment]
@jordanpadams 

It may have installed locally, but mvn build of validate still prefers the on the net.

**Comment by al-niessner** [comment]
@jordanpadams 

Let me know when the new jparser is public available and its version. Still failing.

**Review by nutjob4life — APPROVED** [review]

**Pull request merged**
