### PR TITLE
Update `-u` functionality for updates context products to use new PDS Search API

### LINKED ISSUE #675: Cutover to using new Registry API for generating context products json
## 💡 Description

Update `-u` flag functionality to query API instead of legacy registry.

### PR DESCRIPTION
**Pull request by al-niessner**
## 🗒️ Summary
Instead of using Solr to read the old database, use simple http to read from an registry-api instead.

## ⚙️ Test Data and/or Report
NA - run validate -u and look at the JSON it generates

## ♻️ Related Issues
Closes #675

### CODE REVIEW

**Comment by al-niessner** [comment]
Notes:

1. because of pagination, takes forever to run just up to the 10000
2. because registry-api does not have 10000 fix so when that is applied it will take longer
3. odd difference between curl and Java that do not get expected registry file (empty with java while filled with curl)
    a. same URL (double checked)
    b. when fed curl version of data, Java produces expected file
    c. hence, it really is something weird between Java and curl

**Review by nutjob4life — APPROVED** [review]

**Comment by jordanpadams** [comment]
@al-niessner based upon your comment above, does that mean we actually do not get all the context products? Or are there more than 10000?

**Comment by jordanpadams** [comment]
@al-niessner ☝️

**Comment by jordanpadams** [comment]
Pausing the merger of this PR until:
1. we can guarantee the accuracy of the context products loaded.
2. Pagination performance improves

**Pull request closed without merging**
