### PR TITLE
Minimally handle SEED files and fix automated test caching issue

### LINKED ISSUE #1028: validate incorrectly disallows Encoded_Native/encoding_standard_id = 'SEED 2.4'
### Checked for duplicates

No - I haven't checked

### 🐛 Describe the bug

I hope this isn't an artifact of using a preliminary version of 1N00.
The attached .xml file is Product_Native. It should pass validation, but instead gives an ERROR about "...encoding parameter 'SEED 2.4' is not known to this version of validate"

### 🕵️ Expected behavior

Complete PASS of the input file

### 📜 To Reproduce
```
% validate -x PDS4_PDS_1N00.xsd -S PDS4_PDS_1N00.sch -t xa.s16..shz.1976.070.0.xml
PDS Validate Tool Report
Configuration:
   Version     3.6.0-SNAPSHOT
   Date        2024-10-11T20:51:03Z
Parameters:
   Targets                        [file:/Users/rchen/Desktop/val/xa.s16..shz.1976.070.0.xml]
   User Specified Schemas         [file:/Users/rchen/Desktop/val/PDS4_PDS_1N00.xsd]
   User Specified Schematrons     [file:/Users/rchen/Desktop/val/PDS4_PDS_1N00.sch]
   Severity Level                 WARNING
   Recurse Directories            true
   File Filters Used              [*.xml, *.XML]
   Data Content Validation        on
   Product Level Validation       on
   Max Errors                     100000
   Registered Contexts File       /Users/rchen/PDS4tools/validate/resources/registered_context_products.json
Product Level Validation Results
  FAIL: file:/Users/rchen/Desktop/val/xa.s16..shz.1976.070.0.xml
      ERROR  [error.validation.internal_error]   Could not process the encoding type: encoding parameter 'SEED 2.4' is not known to this version of validate.
        1 product validation(s) completed
Summary:
  1 product(s)
  1 error(s)
  0 warning(s)
  Product Validation Summary:
    0          product(s) passed
    1          product(s) failed
    0          product(s) skipped
    1          product(s) total
  Referential Integrity Check Summary:
    0          check(s) passed
    0          check(s) failed
    0          check(s) skipped
    0          check(s) total
  Message Types:
    1            error.validation.internal_error
End of Report
Completed execution in 1676 ms
```

### ⚙️ Engineering Details

Follow-on task: https://github.com/NASA-PDS/pds4-information-model/issues/825

### 🎉 Integration & Test

_No response_

### PR DESCRIPTION
**Pull request by al-niessner**
## 🗒️ Summary
Added to allowable mime types and how that maps to extensions.

## ⚙️ Test Data and/or Report
All unit tests below should pass but specifically 1028

## ♻️ Related Issues
Closes #1028

### CODE REVIEW

**Review by nutjob4life — COMMENTED** [review]
Tried to do `mvn clean package` but I got:

    [ERROR] Tests run: 269, Failures: 101, Errors: 0, Skipped: 23

Is there an external dependency I need to update?

**Comment by al-niessner** [comment]
@nutjob4life 

Nope. It is simply broken. I have a really good case where the injection of schematron at test 1 is causing an error in test 8 because it thinks the model version should match the injected schematron. Maybe I can figure out what cache is not being emptied now.

**Comment by nutjob4life** [comment]
@al-niessner oh okay, no problem! Thanks for letting me know!

**Comment by al-niessner** [comment]
@jordanpadams @nutjob4life @tloubrieu-jpl 

It is ready for release. The tests now all run on my laptop successfully. Waiting for github actions but my expectation is that they will pass. Two important things beyond this actual ticket:
1. The schema(tron) caches are now cleared. Using this ticket, I was able to uncover the mole sequestering the hidden caches.
2. Will now always fail on internal error. Well it works well for surprises, we should not accept surprises in our regression testing. Turns out that 9 tests were/are failing because it is generating internal errors when it should not be. Marked them and created #1058 so that y'all can schedule when you want to fix them. They are not trivial.

**Comment by jordanpadams** [comment]
> The schema(tron) caches are now cleared. Using this ticket, I was able to uncover the mole sequestering the hidden caches.

@al-niessner this is very exciting! Great work! This mole has roamed free for many years. He must be the mole from Caddyshack. He has been harassing Bill Murray for too long...

**Review by jordanpadams — APPROVED** [review]

**Comment by nutjob4life** [comment]
@jordanpadams is too fast; I only just now got:
```
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
```
Anyway, wooooot! 🎉

**Pull request merged**
