### PR TITLE
Initial validation checks that filenames match valid audio/video formats per CCB-325

### PR DESCRIPTION
**Pull request by al-niessner**
## 🗒️ Summary
Brief summary of changes if not sufficiently described by commit messages.

## ⚙️ Test Data and/or Report
See unit tests below

## ♻️ Related Issues
#604 
#605

### CODE REVIEW

**Comment by al-niessner** [comment]
@jordanpadams 

This passes locally with the schema/schematron being local as well. It will be ready for merge when 1K00 is published and the unit tests pass.

**Review by nutjob4life — APPROVED** [review]
👍

**Comment by jordanpadams** [comment]
@al-niessner can you take a look at what is happening with the tests? The 1K00 dictionaries are online and should be available. I did update the files to look for the 1K00 LDDs.

**Comment by al-niessner** [comment]
@jordanpadams ready but does not do a binary check. I suggest that be another ticket if it is really an issue. It will take a month or two of work with some sketchy third party libraries to verify the container is correct and then all frames are properly encoded. A 10 minute movie is going to take more than 10 minutes probably because validate cannot always guarantee  a video card is present to do the heavy lifting.

If you want it done on this ticket, then tell me and it will become a priority.

**Comment by jordanpadams** [comment]
@al-niessner copy. I create some new sub-tasks for the content validation.

**Pull request merged**
