### PR TITLE
Issue #24: Retrieve and use latest context products from EN Registry

### LINKED ISSUE #24: Update context check to retrieve and use latest context products from EN Registry
The context reference validation feature that has been added to Validate Tool is just a short term solution. I think in the long run, we will want to go out to the EN Registry to find the latest context products.

Basically there would be an additional class / method added to the Validate source to perform this remote check of the EN Registry.

I would think it should replace the JSON file that comes with the delivered software (backup the old version), that way if they do not have an internet connection, it will validate with the latest based upon when the user last ran the tool.

Requirements: Add a `-u`, update,  flag that forces the tool to try to download the latest set of context products (and replace the existing file).

See also closed pull request on private repo: https://github.jpl.nasa.gov/PDSEN/pds4-java/pull/114

### PR DESCRIPTION
**Pull request by jordanpadams**
Added a flag (-u) that specifies that the latest JSON context should be
download (and replace the existing file).

Modified classes in tools package to make sure all classes should be
inside tools package.

Resolves #24

### CODE REVIEW

**Comment by jordanpadams** [comment]
@danyu-pds since there are no integration/unit tests, can you please provide the data (URL or attached) you used to test this and a test case that can be run?

**Comment by danyu-pds** [comment]
> @danyu-pds since there are no integration/unit tests, can you please provide the data (URL or attached) you used to test this and a test case that can be run?

- Run the script:
bin/validate -u

- Then check the files in resources:
resources/registered_context_products.json.backup
resources/registered_context_products.json

- Also compare registered_context_products.json with the the file which get from the URL:
first use this
https://pds.nasa.gov/services/search/archive-filter?q=product_class:Product_Context&wt=json
to get the number of found:
response |  
-- | --
numFound | 1881

Then use this to get all records:
https://pds.nasa.gov/services/search/archive-filter?q=product_class:Product_Context&wt=json&start=0&rows=1881

**Comment by danyu-pds** [comment]
@jordanpadams 
I have added the SolrJ dependency in the pom.xml. Not sure why you add it again?

**Comment by jordanpadams** [comment]
> @jordanpadams
> I have added the SolrJ dependency in the pom.xml. Not sure why you add it again?

@danyu-pds that was an oversight on my part in my review of the pom.xml. should be good to go now.

**Review by danyu-pds — APPROVED** [review]
Check out the branch, modified the pom.xml file and test it. It looks good to me.

**Pull request merged**
