### PR TITLE
Update special constants validation to support bit patterns

### LINKED ISSUE #651: As a user, I want to support bit patterns within Special_Constants values
### Checked for duplicates

No - I haven't checked

### 🧑‍🔬 User Persona(s)

Data Engineer, Data Provider

### 💪 Motivation

...so that I can use bit patterns in most (it not all) Special_Constants attributes

### 📖 Additional Details

_No response_

### Acceptance Criteria

**Given** 
**When I perform** 
**Then I expect** 

### ⚙️ Engineering Details

Related to discussion starting here: https://github.com/NASA-PDS/validate/issues/611#issuecomment-1555457236

### PR DESCRIPTION
**Pull request by al-niessner**
## 🗒️ Summary
Expand the processing of special constants to handle 0x and 16# plus octal and binary.

## ⚙️ Test Data and/or Report
Squeezed in a unit test but really need to look at #659 so see unit tests below as well as this messaging:
```
PDS Validate Tool Report

Configuration:
   Version                       3.3.0-SNAPSHOT
   Date                          2023-06-29T21:49:32Z

Parameters:
   Targets                       [file:/home/niessner/Projects/PDS/validate/src/test/resources/M1431146123CC.xml]
   Severity Level                WARNING
   Recurse Directories           true
   File Filters Used             [*.xml, *.XML]
   Data Content Validation       on
   Product Level Validation      on
   Max Errors                    100000
   Registered Contexts File      /home/niessner/Projects/PDS/validate/src/main/resources/util/registered_context_products.json



Product Level Validation Results

  PASS: file:/home/niessner/Projects/PDS/validate/src/test/resources/M1431146123CC.xml
        1 product validation(s) completed
Jun 29, 2023 2:49:47 PM gov.nasa.pds.tools.validate.task.ValidationTask execute
INFO: Validation complete for location 'file:/home/niessner/Projects/PDS/validate/src/test/resources/M1431146123CC.xml'

Summary:

  0 error(s)
  0 warning(s)

  Product Validation Summary:
    1          product(s) passed
    0          product(s) failed
    0          product(s) skipped

  Referential Integrity Check Summary:
    0          check(s) passed
    0          check(s) failed
    0          check(s) skipped


End of Report
Completed execution in 16672 ms
```

## ♻️ Related Issues
Closes #651

### CODE REVIEW

**Review by jordanpadams — CHANGES_REQUESTED** [review]
@al-niessner looks great! can we add a test case or 2 or 3 for this?

**Comment by al-niessner** [comment]
> @al-niessner looks great! can we add a test case or 2 or 3 for this?

Not without moving to large file git (#659) or something else. Git is getting very unhappy with are large files that seem to only be getting bigger.

**Comment by jordanpadams** [comment]
> > @al-niessner looks great! can we add a test case or 2 or 3 for this?
> 
> Not without moving to large file git (#659) or something else. Git is getting very unhappy with are large files that seem to only be getting bigger.

ok then. unit test? if not, we will have to deal with this for now. will look at #659 after we close out some of these registry bugs.

**Comment by al-niessner** [comment]
@jordanpadams added unit test for this ticket and ready to be merged.

**Review by jordanpadams — APPROVED** [review]

**Pull request merged**
