### PR TITLE
Upgrade to latest SNAPSHOT version of pds4-jparser

### PR DESCRIPTION
**Pull request by jordanpadams**
## 🗒️ Summary
refs https://github.com/NASA-PDS/pds4-jparser/issues/57
refs https://github.com/NASA-PDS/pds4-jparser/pull/82

## ⚙️ Test Data and/or Report
See https://github.com/NASA-PDS/validate/actions/workflows/branch-cicd.yaml
And https://github.com/NASA-PDS/pds4-jparser/actions/workflows/branch-cicd.yaml

### CODE REVIEW

**Comment by jordanpadams** [comment]
Branch CI/CD failed because https://github.com/NASA-PDS/pds4-jparser/pull/82 has not been merged yet. once that is merged. we can rerun those tests

**Review by tloubrieu-jpl — APPROVED** [review]

**Comment by tloubrieu-jpl** [comment]
@jordanpadams , usually I don't create pull request for such change.

**Comment by jordanpadams** [comment]
@tloubrieu-jpl the only reason I did create this PR was so it would run the branch integration tests prior to merging. but since those tests are executed in the unstable build as well, it should be fine either way.

**Comment by jordanpadams** [comment]
Tests completed successfully with latest jparser SNAPSHOT

**Pull request merged**
