### PR TITLE
Fixes bugs with erroneous messages from output logs, duplicate records in collections, and handling of `high_instrument_saturation` special constants

### LINKED ISSUE #831: validate incorrectly handles special constant high_instrument_saturation
### Checked for duplicates

No - I haven't checked

### 🐛 Describe the bug

When I validate the attached, validate correctly flags values that match missing_constant, high_representation_saturation, valid_minimum, low_instrument_saturation, low_representation_saturation but misses a value that matches high_instrument_saturation and instead flags that value as being below valid_minimum (which is true, but so are the other values).

### 🕵️ Expected behavior

I expected the three values for which validate threw WARNINGs about below minimum to be INFOs about matching a special constant

### 📜 To Reproduce

```
% ./validate-3.5.0-SNAPSHOT/bin/validate -v1 -t kplo.xml
PDS Validate Tool Report
Configuration:
   Version     3.5.0-SNAPSHOT
   Date        2024-02-20T21:01:33Z
Parameters:
   Targets                      [file:/Users/rchen/Desktop/kplo.xml]
   Severity Level               INFO
   Recurse Directories          true
   File Filters Used            [*.xml, *.XML]
   Data Content Validation      on
   Product Level Validation     on
   Max Errors                   100000
   Registered Contexts File     /Users/rchen/Desktop/validate-3.5.0-SNAPSHOT/resources/registered_context_products.json
Product Level Validation Results
  PASS: file:/Users/rchen/Desktop/kplo.xml
      INFO  [info.label.filesize_matches]   Generated filesize '513' matches the supplied filesize '513' in the product label for 'file:/Users/rchen/Desktop/kplo.cub'
      INFO  [info.label.context_ref_found]   line 50: Context product found: 'urn:kari:kpds:context:investigation:mission.kplo'
      INFO  [info.label.context_ref_found]   line 60: Context product found: 'urn:kari:kpds:context:instrument_host:spacecraft.kplo'
      INFO  [info.label.context_ref_found]   line 68: Context product found: 'urn:kari:kpds:context:instrument:kplo.shc'
      INFO  [info.label.context_ref_found]   line 77: Context product found: 'urn:nasa:pds:context:target:planet.earth'
      INFO  [info.label.context_ref_found]   line 85: Context product found: 'urn:nasa:pds:context:target:satellite.earth.moon'
      INFO  [info.label.local_identifier_found]   line 94: Referenced Local Identifier 'DATA_FILE' found in label on line '119'.
      INFO  [info.label.local_identifier_found]   line 104: Referenced Local Identifier 'Array_2D_Image' found in label on line '126'.
    Begin Content Validation: file:/Users/rchen/Desktop/kplo.cub
      WARNING  [warning.array.value_out_of_special_constant_min_max_range]   array 1, location (7, 1): Field has a value '-3.4028233E38' that is less than the defined minimum value '0xFF7FFFFA'. 
      INFO  [info.array.is_special_constant]   array 1, location (7, 2): Value is a special constant defined in the label: -3.4028225E38
      INFO  [info.array.is_special_constant]   array 1, location (7, 3): Value is a special constant defined in the label: -3.4028227E38
      INFO  [info.array.is_special_constant]   array 1, location (7, 4): Value is a special constant defined in the label: -3.4028229E38
      INFO  [info.array.is_special_constant]   array 1, location (7, 5): Value is a special constant defined in the label: -3.402823E38
      WARNING  [warning.array.value_out_of_special_constant_min_max_range]   array 1, location (7, 6): Field has a value '-3.4028233E38' that is less than the defined minimum value '0xFF7FFFFA'. 
      INFO  [info.array.is_special_constant]   array 1, location (7, 7): Value is a special constant defined in the label: -3.4028235E38
      WARNING  [warning.array.value_out_of_special_constant_min_max_range]   array 1, location (7, 8): Field has a value '-3.4028233E38' that is less than the defined minimum value '0xFF7FFFFA'. 
    End Content Validation: file:/Users/rchen/Desktop/kplo.cub
        1 product validation(s) completed
Summary:
  1 product(s)
  0 error(s)
  3 warning(s)
  Product Validation Summary:
    1          product(s) passed
    0          product(s) failed
    0          product(s) skipped
    1          product(s) total
  Referential Integrity Check Summary:
    0          check(s) passed
    0          check(s) failed
    0          check(s) skipped
    0          check(s) total
  Message Types:
    5            info.array.is_special_constant
    5            info.label.context_ref_found
    1            info.label.filesize_matches
    2            info.label.local_identifier_found
    3            warning.array.value_out_of_special_constant_min_max_range
End of Report
Completed execution in 2297 ms
```

### 📚 Version of Software Used

Both 3.5.0-SNAPSHOT on 2024-02-20T21:01:33Z and 3.4.1 on 2024-02-20T20:53:17Z do this

### 🩺 Test Data / Additional context

Here's the relevant section of a hex dump of the attached file kplo.cub:
```000000c0: feff 7fff faff 7fff fbff 7fff fcff 7fff  ................```
```000000d0: fdff 7fff feff 7fff ffff 7fff feff 7fff  ................```

Note that because it's LSB, the ordering is backwards from what the xml has, which is:
```        <missing_constant>0xFF7FFFFB</missing_constant>
        <high_instrument_saturation>0xFF7FFFFE</high_instrument_saturation>
        <high_representation_saturation>0xFF7FFFFF</high_representation_saturation>
        <valid_minimum>0xFF7FFFFA</valid_minimum>
        <low_instrument_saturation>0xFF7FFFFD</low_instrument_saturation>
        <low_representation_saturation>0xFF7FFFFC</low_representation_saturation>
```
Ideally, all 8 values in kplo.cub would throw INFOs. It would also be logically consistent if 7 of them threw WARNINGs. The actual result is odd, that only the 3 floats matching high_instrument_saturation throw a WARNING.

[kplo.zip](https://github.com/NASA-PDS/validate/files/14351194/kplo.zip)

### 🦄 Related requirements

🦄 #xyz

### ⚙️ Engineering Details

_No response_

### LINKED ISSUE #832: Review Handling of Special Constants, Field Formats, and High Priority Bug Fixes
### 💡 Description

It appears we have some improvements needed for handling of special constants and field formats according to the standards and what errors/warnings/info messages should be output to to the user.

### 👶 Child Tasks

- #849
- #854 
- #873
- #874
- #880
- #831 
- #817 
- #816 
- #837
- #903

### LINKED ISSUE #849: Validate stalls when validating collection inventory file with duplicates records
### Checked for duplicates

Yes - I've already checked

### 🐛 Describe the bug

Validate crashes using this command:

validate_350 -t *.XML -r log.txt --schema PDS4_LADEE_1L00_1100.xsd --schematron PDS4_LADEE_1L00_1100.schwhen validating XML / CSV file using this command:

### 🕵️ Expected behavior

I expected Validate to not crash and complete the validation

### 📜 To Reproduce

1.   Unzip the 2 zip files in separate directories
2.   execute Validate using the above command
3.   1 zip should fail and 1 zip should complete
4.   Compare XMS and CSV files for differences

### 🖥 Environment Info

- Version of this software -- validate_3.5.0 
- Operating System -- Windows

### 📚 Version of Software Used

validate_3.5.0 

### 🩺 Test Data / Additional context

(1) data_raw.zip contains the amended files that Validate accurately validates
(2) validate_error.zip contains the original files that caused Validate to crash.
(3) As far as I can tell, the CSV file contained 2 duplicate records -- which when deleted, allowed validate to not crash

[data_raw.zip](https://github.com/NASA-PDS/validate/files/14485163/data_raw.zip)
[aaaValidate_Error.zip](https://github.com/NASA-PDS/validate/files/14485165/aaaValidate_Error.zip)

### 🦄 Related requirements

🦄 #xyz

### ⚙️ Engineering Details

_No response_

### LINKED ISSUE #854: validate 3.5.0-SNAPSHOT attempts to look at all files, not just *.xml
### Checked for duplicates

Yes - I've already checked

### 🐛 Describe the bug

When I use validate 3.5.0-SNAPSHOT to validate a bundle with pds4.bundle, I noticed that it prints Error messages that looks like it's checking EVERY file to see if it's a label and not just *.xml and *.XML as it claims it is using for in file filters.  It doesn't include these messages in a report when writing to a report file, but it does fill the terminal with a lot of confusing messages similar to the following:
`Error on line 1 column 1 of NAC_ANAGLYPH_M1101296365_M1101289222.BROWSE.PNG:
  SXXP0003   Error reported by XML parser: Invalid byte 1 of 1-byte UTF-8 sequence.`

### 🕵️ Expected behavior

I expected validate to just look at the files that it claims to be looking at and not whine about the files that it shouldn't be looking at not being a label.

### 📜 To Reproduce

1.  validate a bundle with -R pds4.bundle
2. watch the error messages roll across the screen
...

### 🖥 Environment Info

- Version of this software [3.5.0-SNAPSHOT]
- Operating System: Linux with openjdk 11.0.19

### 📚 Version of Software Used

_No response_

### 🩺 Test Data / Additional context

_No response_

### 🦄 Related requirements

_No response_

### ⚙️ Engineering Details

_No response_

### I&T
TestRail Test ID: T8833815

### LINKED ISSUE #874: SXXP0003 Error when running on PDS3 data sets for v3.3.3 or v3.4.1
### Checked for duplicates

Yes - I've already checked

### 🐛 Describe the bug

When I run validate v3.4.1 or v3.3.3 (but not v3.3.0 or before) on a PDS3 data set, my terminal gets flooded with errors that say something like:

> Error on line 1 column 1 of lsb_0408587281_0x53c_eng.lbl:
>  SXXP0003   Error reported by XML parser: Content is not allowed in prolog.: Content is not
>  allowed in prolog.

All error text matches exactly except for the filename.

This does not happen for every file in the PDS3 volume.  But I have seen it for labels describing ascii tables (like index.tab) or FITS files (but not all) or pointing to PNG files.  

When I run an older version of validate (v3.3.0 or v3.1.1), the terminal is not flooded with errors.  The report files match those from above (except for the version line and date stamp).  I'm not sure if this means the all these versions of validate are not reporting an issue in the report file and only now is validate flagging an error in the terminal, or if there is no error.

### 🕵️ Expected behavior

Not sure.  

### 📜 To Reproduce

1. Download [small](https://pdssbn.astro.umd.edu/holdings/nh-a-leisa-2-kem2-v1.0/dataset.shtml) or [larger](https://pdssbn.astro.umd.edu/holdings/nh-a-swap-3-kem2-v1.0/dataset.shtml) example PDS3 data set.
2. Run command:` validate -R pds3.volume`

### 🖥 Environment Info

- Versions of this software: 3.3.3 and 3.4.1 (but not v3.3.0 or v3.1.1)
- Operating System: macOS Monterey Version 12.7.4 and Red Hat Enterprise Linux version 9.3

### 📚 Version of Software Used

gov.nasa.pds:validate
Version 3.3.3
Release Date: 2023-11-20 23:43:57

gov.nasa.pds:validate
Version 3.4.1
Release Date: 2023-12-14 00:22:59

### 🩺 Test Data / Additional context

_No response_

### 🦄 Related requirements

🦄 #xyz

### ⚙️ Engineering Details

_No response_

### PR DESCRIPTION
**Pull request by al-niessner**
## 🗒️ Summary
This is an epic and had many fixes and repairs to the table system in validate.

## ⚙️ Test Data and/or Report
Automated unit tests below should succeed.

## ♻️ Related Issues
Closes #874 
Closes #854 
Closes #849 
Closes #831

### CODE REVIEW

**Comment by jordanpadams** [comment]
@al-niessner are we ready for this to more out of draft?

**Comment by al-niessner** [comment]
Nope

**Comment by al-niessner** [comment]
@jordanpadams @tloubrieu-jpl @nutjob4life 

Moving off this PR at @jordanpadams request. It is ready.

**Review by nutjob4life — APPROVED** [review]
lgtm 👍

**Review by jordanpadams — APPROVED** [review]

**Pull request merged**
