### PR TITLE
Add support to utilize both online and local schema/schematron files

### LINKED ISSUE #599: As a user, I want to be able to use both online and local schema/schematron files.
### Checked for duplicates

Yes - I've already checked

### 🧑‍🔬 User Persona(s)

Anyone that validates a file/collection/bundle against an updated or new schema/schematron that has not been ingested online, while your file/collection/bundle also uses other schema/schematrons that are ingested online.

### 💪 Motivation

So that when I invoke the -x or -S options, I do not have to locally specify every single schema/schematron that a file/bundle/collection references when only one or two are not available online.  It is frustrating when I validate a bundle, the tool gives errors for schema that are easily found online.

### 📖 Additional Details

This may relate to [issue #513](https://github.com/NASA-PDS/validate/issues/513).  

Whenever we have to update a schema/schematron file or if a mission provides a new ldd or if we are testing a new/updated ldd, if the pds4 product label references other schema/schematron files that are completely valid, when I finally run the validate tool and invoke the option -x or -S, the validate tool requires me to specify all schema/schematron files that may be referenced throughout my label/bundle/collection.  This means I have to track down every single reference before, or specify every single possible schema/schematron file.  These options seem to make an all or nothing scenario instead of here are the missing or updated schema/schematrons needed to include in the list.

I would ask that when the -x or -S options are invoked, that the validate tool first checks the files specified by the -x or -S options, and then checks the online posted copies, and then if nothing is found, it should report errors as it does.  

I will also note that when you do not invoke the -x or -S options, and validate finds a schema/schematron in the label it cannot find, it reports a WARNING schema_reference.4: Failed to read schema document and ERROR cvc-complex-type.2.4.c: The matching wildcard is strict, but no declaration can be found for element, whereas if you do invoke the -x or -S options and do not specify all files, it will instead not give warning of missing schema, but will give similar errors as before, but for the online schemas (ex: ERROR [error.label.schema] line XYZ, AB: cvc-complex-type.2.4.c: The matching wildcard is strict, but no declaration can be found for element 'disp:Display_Settings'.  Only when you specify both online missing schemas and the online schemas, do you get no errors or warnings.

### Acceptance Criteria

**Given** 
**When I perform** 
**Then I expect** 

### ⚙️ Engineering Details

_No response_

### PR DESCRIPTION
**Pull request by al-niessner**
## 🗒️ Summary
There was a simple bug preventing the code from doing what is desired. Fixed the bug, then added 4 tests:
1. should work as is
2. provide -x to override with local copy of schema that will generate a single error
3. provide -S to override with local copy of schematron that will generate a single error
4. provide both -x and -S to generate one error because the XSD error prevents the schematron.

## ⚙️ Test Data and/or Report

No Overrides Success
```
$ validate -S src/test/resources/github599/PDS4_PDS_1I00.sch -t src/test/resources/github599/AREA_Camelot_1radii.xml

PDS Validate Tool Report

Configuration:
   Version                       3.3.0-SNAPSHOT
   Date                          2023-04-24T19:00:22Z

Parameters:
   Targets                       [file:/home/niessner/Projects/PDS/validate/src/test/resources/github599/AREA_Camelot_1radii.xml]
   Severity Level                WARNING
   Recurse Directories           true
   File Filters Used             [*.xml, *.XML]
   Data Content Validation       on
   Product Level Validation      on
   Max Errors                    100000
   Registered Contexts File      /home/niessner/Projects/PDS/validate/src/main/resources/util/registered_context_products.json



Product Level Validation Results

  PASS: file:/home/niessner/Projects/PDS/validate/src/test/resources/github599/AREA_Camelot_1radii.xml
      WARNING  [warning.label.schematron]   line 48, 35: The value Spacecraft for attribute Observing_System_Component.type is deprecated and should not be used.
        1 product validation(s) completed
Apr 24, 2023 12:00:27 PM gov.nasa.pds.tools.validate.task.ValidationTask execute
INFO: Validation complete for location 'file:/home/niessner/Projects/PDS/validate/src/test/resources/github599/AREA_Camelot_1radii.xml'

Summary:

  0 error(s)
  1 warning(s)

  Product Validation Summary:
    1          product(s) passed
    0          product(s) failed
    0          product(s) skipped

  Referential Integrity Check Summary:
    0          check(s) passed
    0          check(s) failed
    0          check(s) skipped

  Message Types:
    1            warning.label.schematron

End of Report
```

Override Schema Failure:
```
$ validate -x src/test/resources/github599/PDS4_PDS_1I00.xsd -t src/test/resources/github599/AREA_Camelot_1radii.xml

PDS Validate Tool Report

Configuration:
   Version                       3.3.0-SNAPSHOT
   Date                          2023-04-24T18:47:48Z

Parameters:
   Targets                       [file:/home/niessner/Projects/PDS/validate/src/test/resources/github599/AREA_Camelot_1radii.xml]
   User Specified Schemas        [file:/home/niessner/Projects/PDS/validate/src/test/resources/github599/PDS4_PDS_1I00.xsd]
   Severity Level                WARNING
   Recurse Directories           true
   File Filters Used             [*.xml, *.XML]
   Data Content Validation       on
   Product Level Validation      on
   Max Errors                    100000
   Registered Contexts File      /home/niessner/Projects/PDS/validate/src/main/resources/util/registered_context_products.json



Product Level Validation Results

  FAIL: file:/home/niessner/Projects/PDS/validate/src/test/resources/github599/AREA_Camelot_1radii.xml
      ERROR  [error.label.schema]   line 12, 25: cvc-complex-type.2.4.a: Invalid content was found starting with element '{"http://pds.nasa.gov/pds4/pds/v1":logical_identifier}'. One of '{"http://pds.nasa.gov/pds4/pds/v1":logical_id}' is expected.
        1 product validation(s) completed
Apr 24, 2023 11:47:50 AM gov.nasa.pds.tools.validate.task.ValidationTask execute
INFO: Validation complete for location 'file:/home/niessner/Projects/PDS/validate/src/test/resources/github599/AREA_Camelot_1radii.xml'

Summary:

  1 error(s)
  0 warning(s)

  Product Validation Summary:
    0          product(s) passed
    1          product(s) failed
    0          product(s) skipped

  Referential Integrity Check Summary:
    0          check(s) passed
    0          check(s) failed
    0          check(s) skipped

  Message Types:
    1            error.label.schema

End of Report
```

Override Schematron Failure
```
$ validate -S src/test/resources/github599/PDS4_PDS_1I00.sch  -t src/test/resources/github599/AREA_Camelot_1radii.xml

PDS Validate Tool Report

Configuration:
   Version                       3.3.0-SNAPSHOT
   Date                          2023-04-24T18:54:19Z

Parameters:
   Targets                       [file:/home/niessner/Projects/PDS/validate/src/test/resources/github599/AREA_Camelot_1radii.xml]
   User Specified Schematrons    [file:/home/niessner/Projects/PDS/validate/src/test/resources/github599/PDS4_PDS_1I00.sch]
   Severity Level                WARNING
   Recurse Directories           true
   File Filters Used             [*.xml, *.XML]
   Data Content Validation       on
   Product Level Validation      on
   Max Errors                    100000
   Registered Contexts File      /home/niessner/Projects/PDS/validate/src/main/resources/util/registered_context_products.json



Product Level Validation Results

  FAIL: file:/home/niessner/Projects/PDS/validate/src/test/resources/github599/AREA_Camelot_1radii.xml
      WARNING  [warning.label.schematron]   line 48, 35: The value Spacecraft for attribute Observing_System_Component.type is deprecated and should not be used.
      ERROR  [error.label.schematron]   line 50, 15: The attribute pds:Observing_System_Component/pds:type must be equal to one of the following values 'Airborne', 'Aircraft', 'Artificial Illumination', 'Balloon', 'Computer', 'Facility', 'Host', 'Instrument', 'Laboratory', 'Literature Search', 'Naked Eye', 'Observatory', 'Spacecraft', 'Suborbital Rocket', 'Telescope'.
        1 product validation(s) completed
Apr 24, 2023 11:54:23 AM gov.nasa.pds.tools.validate.task.ValidationTask execute
INFO: Validation complete for location 'file:/home/niessner/Projects/PDS/validate/src/test/resources/github599/AREA_Camelot_1radii.xml'

Summary:

  1 error(s)
  1 warning(s)

  Product Validation Summary:
    0          product(s) passed
    1          product(s) failed
    0          product(s) skipped

  Referential Integrity Check Summary:
    0          check(s) passed
    0          check(s) failed
    0          check(s) skipped

  Message Types:
    1            error.label.schematron
    1            warning.label.schematron

End of Report
```

Override Schema+Schematron Failure
```
$ validate -S src/test/resources/github599/PDS4_PDS_1I00.sch -x src/test/resources/github599/PDS4_PDS_1I00.xsd -t src/test/resources/github599/AREA_Camelot_1radii.xml

PDS Validate Tool Report

Configuration:
   Version                       3.3.0-SNAPSHOT
   Date                          2023-04-24T18:55:51Z

Parameters:
   Targets                       [file:/home/niessner/Projects/PDS/validate/src/test/resources/github599/AREA_Camelot_1radii.xml]
   User Specified Schemas        [file:/home/niessner/Projects/PDS/validate/src/test/resources/github599/PDS4_PDS_1I00.xsd]
   User Specified Schematrons    [file:/home/niessner/Projects/PDS/validate/src/test/resources/github599/PDS4_PDS_1I00.sch]
   Severity Level                WARNING
   Recurse Directories           true
   File Filters Used             [*.xml, *.XML]
   Data Content Validation       on
   Product Level Validation      on
   Max Errors                    100000
   Registered Contexts File      /home/niessner/Projects/PDS/validate/src/main/resources/util/registered_context_products.json



Product Level Validation Results

  FAIL: file:/home/niessner/Projects/PDS/validate/src/test/resources/github599/AREA_Camelot_1radii.xml
      ERROR  [error.label.schema]   line 12, 25: cvc-complex-type.2.4.a: Invalid content was found starting with element '{"http://pds.nasa.gov/pds4/pds/v1":logical_identifier}'. One of '{"http://pds.nasa.gov/pds4/pds/v1":logical_id}' is expected.
      WARNING  [warning.label.schematron]   line 48, 35: The value Spacecraft for attribute Observing_System_Component.type is deprecated and should not be used.
      ERROR  [error.label.schematron]   line 50, 15: The attribute pds:Observing_System_Component/pds:type must be equal to one of the following values 'Airborne', 'Aircraft', 'Artificial Illumination', 'Balloon', 'Computer', 'Facility', 'Host', 'Instrument', 'Laboratory', 'Literature Search', 'Naked Eye', 'Observatory', 'Spacecraft', 'Suborbital Rocket', 'Telescope'.
        1 product validation(s) completed
Apr 24, 2023 11:55:53 AM gov.nasa.pds.tools.validate.task.ValidationTask execute
INFO: Validation complete for location 'file:/home/niessner/Projects/PDS/validate/src/test/resources/github599/AREA_Camelot_1radii.xml'

Summary:

  2 error(s)
  1 warning(s)

  Product Validation Summary:
    0          product(s) passed
    1          product(s) failed
    0          product(s) skipped

  Referential Integrity Check Summary:
    0          check(s) passed
    0          check(s) failed
    0          check(s) skipped

  Message Types:
    1            error.label.schematron
    1            error.label.schema
    1            warning.label.schematron

End of Report
```

## ♻️ Related Issues
Closes #599

### CODE REVIEW

**Review by nutjob4life — APPROVED** [review]
👍

**Review by nutjob4life — APPROVED** [review]
Approved … again! 👍

**Comment by nutjob4life** [comment]
Maybe this PR should be marked as a draft? There have been a lot of commits since my first two approvals 🤷

**Comment by al-niessner** [comment]
@nutjob4life Sorry but the cucumber file is giving me lots of grief for reasons my eye is having a very hard detecting. I probably should write a script to check that the features file is going to be interpreted well enough.

**Comment by nutjob4life** [comment]
@al-niessner no worries, no rush!

**Comment by al-niessner** [comment]
@jordanpadams @nutjob4life @tloubrieu-jpl 

Who is the expert on cucumber and the validate tests that run in Jenkins? I am getting a different result from the command line and Jenkins.

On mine:

```
Parameters:
   Targets                       [file:/home/niessner/Projects/PDS/validate/src/test/resources/github599/AREA_Camelot_1radii.xml]
   User Specified Schemas        [file:/home/niessner/Projects/PDS/validate/src/test/resources/github599/PDS4_PDS_1I00.xsd]
><...snip...><
  FAIL: file:/home/niessner/Projects/PDS/validate/src/test/resources/github599/AREA_Camelot_1radii.xml
      ERROR  [error.label.schema]   line 12, 25: cvc-complex-type.2.4.a: Invalid content was found starting with element '{"http://pds.nasa.gov/pds4/pds/v1":logical_identifier}'. One of '{"http://pds.nasa.gov/pds4/pds/v1":logical_id}' is expected.
```

but on Jenkins

```
[file:/home/runner/work/validate/validate/src/test/resources/github599/AREA_Camelot_1radii.xml]","userSpecifiedSchemas":"[file:/home/runner/work/validate/validate/src/test/resources/github599/PDS4_PDS_1I00.xsd]","severityLevel":"WARNING","recurseDirectories":"true","fileFiltersUsed":"[*.xml, *.XML]","dataContentValidation":"on","productLevelValidation":"on","maxErrors":"100000","registeredContextsFile":"/home/runner/work/validate/validate/src/main/resources/util/registered_context_products.json"},"productLevelValidationResults":[{"status":"PASS","label":"file:/home/runner/work/validate/validate/src/test/resources/github599/AREA_Camelot_1radii.xml","messages":[{"severity":"WARNING","type":"warning.label.schematron","line":48,"column":35,"message":"The value Spacecraft for attribute Observing_System_Component.type is deprecated and should not be used."}],"fragments":[],"dataContents":[]}],"summary":{"totalProducts":1,"totalErrors":0,"totalWarnings":1,"messageTypes":[{"messageType":"warning.label.schematron","total":1}]}} ==> expected: <0> but was: <1>
```

It seems that -x is overriding downloading but not whatever is happening on Jenkins runs. Who is the expert to help sort this out -- I am going to take a wild stab and say it is testing defined a schema dir in core.properties and it is not being overridden?

Do we want to ignore this (not add the unit tests and just trust me) or pursue to its grizzly end? Moving to another ticket until then...

**Comment by jordanpadams** [comment]
@al-niessner we have experienced this weirdness on occasion with the ordering of the tests in cucumber. for whatever reason cucumber does not flush the java cache between tests (even if we try to force it), so it is using previous test information and throwing errors. maybe play around with the ordering of tests in the features file? maybe move it to the very bottom?

**Comment by al-niessner** [comment]
@jordanpadams

I already tried order and more casting suspicions on the cache because my
-S makes almost all tests fail. Seems prudent to remove this unit test and
call it done.

**Review by jordanpadams — APPROVED** [review]

**Pull request merged**
