### PR TITLE
Update functionality to throw ERROR for `validation_format` mismatch, and WARNING for `field_format` mismatch.

### LINKED ISSUE #816: As a user, I want a WARNING to be thrown when a delimited or character table value does not match the expected `field_format`
### Checked for duplicates

Yes - I've already checked

### 🧑‍🔬 User Persona(s)

Data User, Data Archivist

### 💪 Motivation

...so that I can be warned when a field's value does not meet the expectations of the `field_format`, but should not be an error.

Treat precision as "maximum precision" instead of "exact precision".

Add additional flag to disable this check.

### 📖 Additional Details

From SR:
> 4B.1.2 Field Formats
>  
> Attributes <field_format> and <validation_format> give the magnitude and precision of the data value.
>  
> <field_format> describes the general format of a value in a field. For binary tables, this is used to format the value for output, particularly to specify the appropriate number of significant digits when converting real values.
>  
> For character tables, <field_format> is used to describe the maximum length and alignment of the data. <field_format> also gives an indication of the maximum precision of real numbers, but does not require all values to have this precision.
>  
> <validation_format> is used with character tables to further constrain a field’s values. When a <validation_format> is present, the data in a table must match the format exactly in order to be valid. Additionally, if <validation_format> is present, it must not conflict with the field format. <validation_format> is not used for binary or delimited tables.
>  
> The specifier used in <field_format> and <validation_format> must be of an integer type if the field data type is a form of integer, or a floating point type if the field data type is a form of float, and of a string type for all other field data types.

field value should match the **exact** format defined by the `validation_format`, unlike the unlike `validation_format`, `field_format` is just a "guide", so we should just throw a WARNING when something doesn't match, and not for precision, this is just a max precision, not an exact precision.

### Acceptance Criteria

**Given** a character table product with `format` defined for a field, and a value in a table that does not match that format
**When I perform** validate on that product
**Then I expect** validate to throw a WARNING the format is not being met
_(automation ID: validate_integration.validate#816)_

### ⚙️ Engineering Details

See test data from #681

### LINKED ISSUE #817: As a user, I want an ERROR to be thrown when a character table value does not match the expected `validation_format`
### Checked for duplicates

Yes - I've already checked

### 🧑‍🔬 User Persona(s)

Data User, Data Archivist

### 💪 Motivation

...so that I can know when when a field's value does not meet the expectations of the `validation_format`

### 📖 Additional Details

From SR:
> 4B.1.2 Field Formats
>  
> Attributes <field_format> and <validation_format> give the magnitude and precision of the data value.
>  
> <field_format> describes the general format of a value in a field. For binary tables, this is used to format the value for output, particularly to specify the appropriate number of significant digits when converting real values.
>  
> For character tables, <field_format> is used to describe the maximum length and alignment of the data. <field_format> also gives an indication of the maximum precision of real numbers, but does not require all values to have this precision.
>  
> <validation_format> is used with character tables to further constrain a field’s values. When a <validation_format> is present, the data in a table must match the format exactly in order to be valid. Additionally, if <validation_format> is present, it must not conflict with the field format. <validation_format> is not used for binary or delimited tables.
>  
> The specifier used in <field_format> and <validation_format> must be of an integer type if the field data type is a form of integer, or a floating point type if the field data type is a form of float, and of a string type for all other field data types.

field value should match the **exact** format defined by the `validation_format`, unlike the `field_format`, which when it comes to precision is <= and should only be a warning.

### Acceptance Criteria

**Given** a character table product with `format` defined for a field, and a value in a table that does not match that format
**When I perform** validate on that product
**Then I expect** validate to throw a WARNING the format is not being met

### ⚙️ Engineering Details

See test data from #681

### PR DESCRIPTION
**Pull request by al-niessner**
## 🗒️ Summary
Error when format_validation and warning when format_value.

## ⚙️ Test Data and/or Report
Automated unit/regression tests below passed.

#816 can be tested by the test cases for #681
#817 includes a new test case in the feature file

## ♻️ Related Issues
Closes #816 
Closes #817

### CODE REVIEW

**Review by nutjob4life — APPROVED** [review]
👍

**Review by jordanpadams — APPROVED** [review]

**Comment by jordanpadams** [comment]
@al-niessner can you confirm if the tests I added checkout? I added one additional test to ensure the `validation_format` is actually throwing an error, versus `field_format` is throwing a warning.

**Comment by al-niessner** [comment]
@jordanpadams 

Do you have a disk space issue? The errors in the latest look like not everything was pulled during the git transaction like you are running out of disk space. The failures are not code they are missing data. You can look at the logs yourself but this is the first clue (starts at line 28932 in log):
```
[INFO] Running cucumber.CucumberTest

Scenario Outline: Execute validate command for tests below.                                                                                                                                                                                                                                             # src/test/resources/features/developer.feature:13
  Given a test "NASA-PDS/validate#873 Success files same name different paths" at dir "github873" at resource "src/test/resources" sending report to "target/test" with "-r {reportDir}/report_github873.json -s json --skip-context-validation -R pds4.bundle -t {resourceDir}/github873" as arguments # cucumber.StepDefs.a_test_string_with_string(java.lang.String,java.lang.String,java.lang.String,java.lang.String,java.lang.String)
  When with test property count 0 text "0 errors expected" problem "totalErrors" reference "report_github873.json"                                                                                                                                                                                      # cucumber.StepDefs.with_test_property(int,java.lang.String,java.lang.String,java.lang.String)
  When execute a validate command                                                                                                                                                                                                                                                                       # cucumber.StepDefs.execute_a_validate_command()
  Then produced output from validate command should be similar to reference "report_github873.json" or no error reported.                                                                                                                                                                               # null

Scenario Outline: Execute validate command for tests below.                                                                                                                                                                                                                                                          # src/test/resources/features/developer.feature:16
  Given a test "NASA-PDS/validate#849 Fails inventory with duplicate entries" at dir "github849" at resource "src/test/resources" sending report to "target/test" with "-r {reportDir}/report_github849.json -s json --skip-context-validation  -t {resourceDir}/github849/collection_uvs_data_raw.xml" as arguments # cucumber.StepDefs.a_test_string_with_string(java.lang.String,java.lang.String,java.lang.String,java.lang.String,java.lang.String)
  When with test property count 2 text "2 errors expected" problem "INVENTORY_DUPLICATE_LIDVID" reference "report_github849.json"                                                                                                                                                                                    # cucumber.StepDefs.with_test_property(int,java.lang.String,java.lang.String,java.lang.String)
..........  When execute a validate command                                                                                                                                                                                                                                                                                    # cucumber.StepDefs.execute_a_validate_command()
  Then produced output from validate command should be similar to reference "report_github849.json" or no error reported.                                                                                                                                                                                            # null
```

**Comment by jordanpadams** [comment]
@al-niessner 😞 I am never fixing a spelling error again. NASA-PDS/validate@cbf6faf8ee538948921d71fd0c70882cf05a5248

**Pull request merged**
