### PR TITLE
Upgrade verapdf to 2.4.0 and switchover to Greenfield Foundry libraries

### LINKED ISSUE #693: Upgrade verapdf dependency per transitive log4j vulnerability
### Checked for duplicates

Yes - I've already checked

### 🐛 Describe the bug

`mvn dependency:tree` I see log4j 1.2.17.

### 🕵️ Expected behavior

I expected no log4j 1.x

### 🦄 Related requirements

🦄 #164

### PR DESCRIPTION
**Pull request by jordanpadams**
When upgrading to verapdf v2.4.0, valid PDFs were inexplicably failing using the PDFBox Foundry version. Even tested them with the downloaded the [verapdf standalone software](https://software.verapdf.org/) and they validated successfully. Switched over to using the alternate Greenfield Foundry libraries instead and everything checks out, so not sure what is going on there. Tests from #164 still work as expected, and added new tests.

In the process of upgrade verapdf, it removed the last remnants of log4j 1.x, which broke several classes in Validate, so this update also includes some changes to support log4j2.

Resolves #693

### CODE REVIEW

**Comment by jordanpadams** [comment]
@rchenatjpl do you have some additional labels / PDFs laying around we could test with this PR to make sure we didn't break anything with this change?

**Comment by rchenatjpl** [comment]
[CLIPPER_RSS_SIS.PDF](https://github.com/NASA-PDS/validate/files/12621824/CLIPPER_RSS_SIS.PDF)

I said this one was PDF/A-3a

**Comment by rchenatjpl** [comment]
[VOLSIS.PDF](https://github.com/NASA-PDS/validate/files/12621852/VOLSIS.PDF)
i said, "This file is not PDF/A-1B or any flavor of PDF/A"

**Comment by rchenatjpl** [comment]
[JIRAM_Overview_Maps_V1.0.pdf](https://github.com/NASA-PDS/validate/files/12621873/JIRAM_Overview_Maps_V1.0.pdf)

just base PDF, not PDF/A

**Comment by rchenatjpl** [comment]
[msi_deblur_golish_etal_draft.pdf](https://github.com/NASA-PDS/validate/files/12621900/msi_deblur_golish_etal_draft.pdf)
PDF/A-2b

**Comment by rchenatjpl** [comment]
@jordanpadams hope it's not too late

**Comment by jordanpadams** [comment]
@nutjob4life @tloubrieu-jpl can I get a review on this today?

**Review by nutjob4life — APPROVED** [review]

**Review by tloubrieu-jpl — APPROVED** [review]

**Comment by tloubrieu-jpl** [comment]
@jordanpadams maybe we should have made that part of the latest release. i can do a point build when it is merged.

**Comment by jordanpadams** [comment]
@tloubrieu-jpl yes. this has to be part of the build. Also, I beleive your attempt at a tag failed so this can still be part of 3.3.0

**Pull request merged**
