### PR TITLE
Fix URL handling on Windows OS

### LINKED ISSUE #902: Validate error during JPEG content validation
### Checked for duplicates

No - I haven't checked

### 🐛 Describe the bug

When running content validation on JPEGs, I get the following error:
ERROR  [error.validation.internal_error]   Error occurred while processing JPEG file content for s_00168901_thm.jpg: Illegal char <:> at index 2: s_00168901_thm.jpg 
Earlier versions of validate (e.g. 3.1.1) don't report this error. I'm not sure what it means, but I'm thinking it's a bug?

### 🕵️ Expected behavior

I didn't expect this error.

### 📜 To Reproduce

run validate on the attached files with content validation
validate validate_error\ -r validate_report.txt

### 🖥 Environment Info

Windows

### 📚 Version of Software Used

v3.5.0-SNAPSHOT

### 🩺 Test Data / Additional context

[validate_error.zip](https://github.com/NASA-PDS/validate/files/15378775/validate_error.zip)

### 🦄 Related requirements

🦄 #xyz

### ⚙️ Engineering Details

_No response_

### 🎉 Integration & Test

_No response_

### PR DESCRIPTION
**Pull request by al-niessner**
## 🗒️ Summary
Quick filename handling update.

## ⚙️ Test Data and/or Report
Automated unit/regression tests all pass (shows fix did not break *nix).

However, cannot replicate error on linux platform so here is output from windows run:
```
PDS Validate Tool Report

Configuration:
   Version     3.6.0-SNAPSHOT
   Date        2024-06-04T22:34:47Z

Parameters:
   Targets                      [file:/c:/Users/niessner/eclipse-workspace/validate/src/test/resources/github902/s_00168901_thm.xml]
   Severity Level               WARNING
   Recurse Directories          true
   File Filters Used            [*.xml, *.XML]
   Data Content Validation      on
   Product Level Validation     on
   Max Errors                   100000
   Registered Contexts File     c:\Users\niessner\eclipse-workspace\validate\src\main\resources\util\registered_context_products.json



Product Level Validation Results

  PASS: file:/c:/Users/niessner/eclipse-workspace/validate/src/test/resources/github902/s_00168901_thm.xml
        1 product validation(s) completed

Summary:

  1 product(s)
  0 error(s)
  0 warning(s)

  Product Validation Summary:
    1          product(s) passed
    0          product(s) failed
    0          product(s) skipped
    1          product(s) total

  Referential Integrity Check Summary:
    0          check(s) passed
    0          check(s) failed
    0          check(s) skipped
    0          check(s) total
```

End of Report
Completed execution in 39262 ms

## ♻️ Related Issues
Closes #902

### CODE REVIEW

**Review by nutjob4life — APPROVED** [review]
LGTM 👍

**Comment by al-niessner** [comment]
@jordanpadams @nutjob4life 

Tweaking these URLs is a full time job. I need to test again on windoze tomorrow to make sure the fixes for linux did not break windoze again.

**Comment by nutjob4life** [comment]
@al-niessner hang in there! That sounds … harrowing 😬

**Comment by al-niessner** [comment]
@jordanpadams @nutjob4life 

Verified it still works on winblows.

**Review by jordanpadams — APPROVED** [review]

**Pull request merged**
