### PR TITLE
New `--complete-descriptions` flag to warn for data not described by metadata in label

### LINKED ISSUE #535: As a user, I want to receive a warning if records in file are greater than records value specified in label
## 🧑‍🔬 User Persona(s)

Data Engineer

## 💪 Motivation
...so that I can know when the records value may be invalid

## 📖 Additional Details

Validate does not, but should, give a warning if "records" in label is less than the actual records in a table. The attached pair, uvis_euv_2008_003_solar_time_series_ingress, passes, but should give a warning.

## ⚖️ Acceptance Criteria
**Given** 
**When I perform** 
**Then I expect** 

## ⚙️ Engineering Details

[insufficient content validation.zip](https://github.com/NASA-PDS/validate/files/9396013/insufficient.content.validation.zip)

### PR DESCRIPTION
**Pull request by al-niessner**
## 🗒️ Summary
Display a warning for data not described by file area at the end of the file.

## ⚙️ Test Data and/or Report
See automated tests below

## ♻️ Related Issues
Closes #535

### CODE REVIEW

**Comment by al-niessner** [comment]
@jordanpadams 

This can easily be extended to include data at the front of the file and between data objects too. Let me know if you want the full set of checks.

**Comment by jordanpadams** [comment]
@al-niessner

let's call it good on this for now. I want the other requirements, but I think we need to get consultation from our data design working group for that.

**Review by jordanpadams — APPROVED** [review]

**Comment by jordanpadams** [comment]
@al-niessner looks like we have a broken test with the new WARNING message.

**Review by jordanpadams — CHANGES_REQUESTED** [review]
@al-niessner looks like we have a broken test with the new WARNING message.

**Comment by al-niessner** [comment]
@jordanpadams 

It is on the original ticket #535 but this change breaks many or most or nearly all of the existing unit tests. There are lots of them that have dodo at the end of their files that adding this as a regular check would be disastrous.

**Review by nutjob4life — APPROVED** [review]
👍

**Comment by al-niessner** [comment]
@jordanpadams ready

**Review by jordanpadams — APPROVED** [review]

**Pull request merged**
